<?php
/**
 * Pure token generation/hashing/comparison primitives.
 *
 * @package Tube_Members
 */

declare(strict_types=1);

namespace Tube_Members\Email;

use DateTimeImmutable;

/**
 * Pure token generation/hashing/comparison primitives — no WordPress
 * calls, no storage, no side effects, fully unit-tested. Deliberately
 * split from {@see EmailVerificationService} the same "pure data + pure
 * decision logic, WordPress-coupled orchestration lives one layer up"
 * posture `Tube_Ads\Placement\PlacementConfig`/`Tube_Comments\Comments\
 * AntiSpam\SpamPolicy` already establish elsewhere in this project — the
 * one piece of this feature actually worth unit-testing in isolation is
 * exactly this: is the token unguessable, is the hash comparison
 * timing-safe, is expiry evaluated correctly, never "does WordPress
 * storage work" (verified instead via live QA, same split every other
 * WP-coupled class in this codebase already uses).
 *
 * The raw token is never stored anywhere — only its hash. A raw token
 * exists only transiently: generated here, put in the emailed link, and
 * compared against by re-hashing whatever the visitor's link submits.
 */
final class VerificationTokenCrypto
{
    /**
     * Raw token length in bytes before hex-encoding (32 bytes = 256 bits
     * of entropy = 64 hex characters) — far beyond brute-force range,
     * the same order of magnitude WordPress core's own password-reset
     * keys use.
     */
    private const TOKEN_BYTES = 32;

    /**
     * Generate a fresh, cryptographically random, one-time raw token —
     * never derived from the user's id/email/timestamp (all three are
     * either public or guessable, which `random_bytes()` deliberately
     * has no relationship to).
     */
    public static function generate_raw_token(): string
    {
        return bin2hex(random_bytes(self::TOKEN_BYTES));
    }

    /**
     * Hash a raw token for at-rest storage — a keyed HMAC, not a bare
     * `hash()`, so recovering a raw token from a leaked hash requires
     * the site's own secret in addition to brute-forcing 256 bits of
     * entropy (defense in depth; the entropy alone already makes that
     * infeasible, the key just means a database-only leak is not even
     * theoretically sufficient).
     *
     * @param string $raw_token The raw token, as generated by {@see self::generate_raw_token()}.
     * @param string $secret    A site-specific secret the caller supplies (never invented here — see
     *                           EmailVerificationService's own use of wp_salt()).
     */
    public static function hash_token(string $raw_token, string $secret): string
    {
        return hash_hmac('sha256', $raw_token, $secret);
    }

    /**
     * Whether $raw_token is the one $stored_hash was made from —
     * timing-safe (`hash_equals()`), never a plain `===` string
     * comparison, which would leak how many leading bytes matched
     * through response-time differences.
     *
     * @param string $stored_hash The hash on file for this user.
     * @param string $raw_token   The raw token submitted via the verification link.
     * @param string $secret      The same secret {@see self::hash_token()} was called with.
     */
    public static function matches(string $stored_hash, string $raw_token, string $secret): bool
    {
        if ('' === $stored_hash || '' === $raw_token) {
            return false;
        }

        return hash_equals($stored_hash, self::hash_token($raw_token, $secret));
    }

    /**
     * The expiry instant for a token generated right now — 24 hours out.
     *
     * @param DateTimeImmutable $now The current moment.
     */
    public static function expires_at(DateTimeImmutable $now): DateTimeImmutable
    {
        return $now->modify('+24 hours');
    }

    /**
     * Whether a stored expiry instant has already passed.
     *
     * @param string            $expires_at_mysql A `Y-m-d H:i:s` instant, as stored in user meta.
     * @param DateTimeImmutable $now              The current moment.
     */
    public static function is_expired(string $expires_at_mysql, DateTimeImmutable $now): bool
    {
        $expires_at = DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $expires_at_mysql);

        if (false === $expires_at) {
            // Malformed/missing expiry can never be treated as still
            // valid -- fail closed, the opposite of every other
            // fail-open posture in this project, because the failure
            // mode here is a token verifying past its intended life,
            // not a visitor being inconvenienced.
            return true;
        }

        return $now > $expires_at;
    }
}
